name: Test of remote action
on: [workflow_dispatch]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        uses: motosongo/hello-world-docker-action/hello-world-docker-action@v1
        id: hello-action
        with:
          who-to-greet: '@octocat'

      - name: Output time set in the container
        run: echo "The time was ${{ steps.hello-action.outputs.time }} when the action said hello"
